--Вывести  EmployeeID,  ShipDate  и  среднее  по  SubTotal  для
--всевозможных EmployeeID с одинаковой ShipDate, предусмотреть
--вывод общего среднего StandardPrice за ShipDate из таблицы
--Purchasing.PurchaseOrderHeader. (Использовать CUBE).